# Generated by Django 3.2.4 on 2021-06-11 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BLImage', models.ImageField(upload_to='bl_images/')),
                ('coloredImage', models.ImageField(blank=True, null=True, upload_to='colored_images/')),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
            },
        ),
    ]
