# Generated by Django 3.2.4 on 2021-06-11 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colorize', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='BLImage',
        ),
        migrations.AddField(
            model_name='image',
            name='BWImage',
            field=models.ImageField(blank=True, null=True, upload_to='bl_images/'),
        ),
    ]
